image: numpy/numpy-gitpod:latest
tasks:
  - name: initialize
    init: |
      mkdir -p .vscode
      echo '{"python.defaultInterpreterPath": "/home/gitpod/mambaforge3/envs/pymc-test-py39/bin/python"}' > .vscode/settings.json
      conda create -yf conda-envs/environment-test-py39.yml
      conda activate pymc-test-py39
      pip install -r requirements-dev.txt
      pip install -e .

vscode:
  extensions:
    - eamodio.gitlens
    - ms-python.python

github:
  prebuilds:
    # enable for master branch
    master: true
    # enable for other branches (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
