blank_issues_enabled: false
contact_links:
  - name: PyMC Discourse
    url: https://discourse.pymc.io/
    about: Ask usage questions about PyMC or doubts about the examples. If not sure where to ask, ask on Discourse.
  - name: PyMC bug report
    url: https://github.com/pymc-devs/pymc/issues
    about: Please report bugs or propose enhancements of the PyMC library here.
