blank_issues_enabled: false
contact_links:
  - name: PyMC Discourse
    url: https://discourse.pymc.io/
    about: Ask usage questions about PyMC3 or doubts about the examples here
  - name: PyMC3 bug report
    url: https://github.com/pymc-devs/pymc3/issues
    about: Please report bugs or propose enhancements of the PyMC3 library here.
