Gallery.contents = {
    "pymc3_howto/api_quickstart": "Basics",
    "variational_inference/variational_api_quickstart": "Basics",
    "PyMC3_and_Theano.rst": "Basics",
    "Probability_Distributions.rst": "Basics",
    "Gaussian_Processes.rst": "Basics",
    "pymc3_howto/data_container": "Basics",
    "pymc3_howto/sampling_compound_step": "Deep dives",
    "pymc3_howto/sampling_callback": "Deep dives",
    "diagnostics_and_criticism/sampler-stats": "Deep dives",
    "diagnostics_and_criticism/Diagnosing_biased_Inference_with_Divergences": "Deep dives",
    "Advanced_usage_of_Theano_in_PyMC3.rst": "Deep dives",
    "getting_started": "Deep dives",
    "ode_models/ODE_API_shapes_and_benchmarking": "Deep dives",
    "samplers/DEMetropolisZ_EfficiencyComparison": "Deep dives",
    "samplers/DEMetropolisZ_tune_drop_fraction": "Deep dives",
    "case_studies/factor_analysis": "Deep dives",
    "case_studies/blackbox_external_likelihood": "How-To",
    "case_studies/blackbox_external_likelihood_no_cython": "How-To",
    "pymc3_howto/profiling": "How-To",
    "pymc3_howto/howto_debugging": "How-To",
    "diagnostics_and_criticism/model_averaging": "How-To",
    "pymc3_howto/updating_priors": "How-To",
    "pymc3_howto/lasso_block_update": "How-To",
    "pymc3_howto/custom_distribution": "How-To"
}
