Gallery.contents = {
    "BART/BART_introduction":"BART",
    "case_studies/BEST": "Case Studies",
    "case_studies/LKJ": "Case Studies",
    "case_studies/stochastic_volatility": "Case Studies",
    "case_studies/rugby_analytics": "Case Studies",
    "case_studies/multilevel_modeling": "Case Studies",
    "case_studies/putting_workflow": "Case Studies",
    "case_studies/moderation_analysis": "Case Studies",
    "case_studies/mediation_analysis": "Case Studies",
    "case_studies/bayesian_ab_testing": "Case Studies",
    "case_studies/item_response_nba": "Case Studies",
    "case_studies/binning": "Case Studies",
    "diagnostics_and_criticism/Diagnosing_biased_Inference_with_Divergences": "Diagnostics and Model Criticism",
    "diagnostics_and_criticism/model_comparison": "Diagnostics and Model Criticism",
    "diagnostics_and_criticism/posterior_predictive": "Diagnostics and Model Criticism",
    "diagnostics_and_criticism/Bayes_factor": "Diagnostics and Model Criticism",
    "generalized_linear_models/GLM": "(Generalized) Linear and Hierarchical Linear Models",
    "generalized_linear_models/GLM-linear": "(Generalized) Linear and Hierarchical Linear Models",
    "generalized_linear_models/GLM-logistic": "(Generalized) Linear and Hierarchical Linear Models",
    "generalized_linear_models/GLM-binomial-regression": "(Generalized) Linear and Hierarchical Linear Models",
    "generalized_linear_models/GLM-hierarchical-binomial-model": "(Generalized) Linear and Hierarchical Linear Models",
    "generalized_linear_models/GLM-hierarchical": "(Generalized) Linear and Hierarchical Linear Models",
    "case_studies/hierarchical_partial_pooling": "(Generalized) Linear and Hierarchical Linear Models",
    "generalized_linear_models/GLM-model-selection": "(Generalized) Linear and Hierarchical Linear Models",
    "generalized_linear_models/GLM-negative-binomial-regression": "(Generalized) Linear and Hierarchical Linear Models",
    "generalized_linear_models/GLM-out-of-sample-predictions": "(Generalized) Linear and Hierarchical Linear Models",
    "generalized_linear_models/GLM-poisson-regression": "(Generalized) Linear and Hierarchical Linear Models",
    "generalized_linear_models/GLM-robust-with-outlier-detection": "(Generalized) Linear and Hierarchical Linear Models",
    "generalized_linear_models/GLM-robust": "(Generalized) Linear and Hierarchical Linear Models",
    "generalized_linear_models/GLM-rolling-regression": "(Generalized) Linear and Hierarchical Linear Models",
    "generalized_linear_models/GLM-truncated-censored-regression": "(Generalized) Linear and Hierarchical Linear Models",
    "generalized_linear_models/GLM-simpsons-paradox": "(Generalized) Linear and Hierarchical Linear Models",
    "gaussian_processes/GP-Kron": "Gaussian Processes",
    "gaussian_processes/GP-Latent": "Gaussian Processes",
    "gaussian_processes/GP-Marginal": "Gaussian Processes",
    "gaussian_processes/GP-MaunaLoa": "Gaussian Processes",
    "gaussian_processes/GP-MaunaLoa2": "Gaussian Processes",
    "gaussian_processes/GP-MeansAndCovs": "Gaussian Processes",
    "gaussian_processes/GP-SparseApprox": "Gaussian Processes",
    "gaussian_processes/GP-TProcess": "Gaussian Processes",
    "gaussian_processes/GP-smoothing": "Gaussian Processes",
    "gaussian_processes/GP-Heteroskedastic": "Gaussian Processes",
    "gaussian_processes/gaussian_process": "Gaussian Processes",
    "case_studies/conditional-autoregressive-model": "Gaussian Processes",
    "case_studies/log-gaussian-cox-process":"Gaussian Processes",
    "gaussian_processes/GP-Circular": "Gaussian Processes",
    "mixture_models/dependent_density_regression": "Mixture Models",
    "mixture_models/dp_mix": "Mixture Models",
    "variational_inference/gaussian-mixture-model-advi": "Mixture Models",
    "mixture_models/gaussian_mixture_model": "Mixture Models",
    "mixture_models/marginalized_gaussian_mixture_model": "Mixture Models",
    "mixture_models/dirichlet_mixture_of_multinomials": "Mixture Models",
    "samplers/SMC2_gaussians": "Simulation-based Inference",
    "samplers/SMC-ABC_Lotka-Volterra_example": "Simulation-based Inference",
    "survival_analysis/bayes_param_survival_pymc3": "Survival Analysis",
    "survival_analysis/censored_data": "Survival Analysis",
    "survival_analysis/survival_analysis": "Survival Analysis",
    "survival_analysis/weibull_aft": "Survival Analysis",
    "survival_analysis/cox_model": "Survival Analysis",
    "time_series/MvGaussianRandomWalk_demo": "Time Series",
    "time_series/AR": "Time Series",
    "time_series/Euler-Maruyama_and_SDEs": "Time Series",
    "time_series/Air_passengers-Prophet_with_Bayesian_workflow": "Time Series",
    "variational_inference/bayesian_neural_network_advi": "Variational Inference",
    "variational_inference/convolutional_vae_keras_advi": "Variational Inference",
    "variational_inference/empirical-approx-overview": "Variational Inference",
    "variational_inference/lda-advi-aevb": "Variational Inference",
    "variational_inference/normalizing_flows_overview": "Variational Inference",
    "variational_inference/gaussian-mixture-model-advi": "Variational Inference",
    "variational_inference/GLM-hierarchical-advi-minibatch": "Variational Inference",
    "ode_models/ODE_with_manual_gradients": "Inference in ODE models",
    "ode_models/ODE_API_introduction": "Inference in ODE models",
    "case_studies/probabilistic_matrix_factorization": "Case Studies",
    "pymc3_howto/sampling_conjugate_step":"MCMC",
    "samplers/MLDA_introduction": "MCMC",
    "samplers/MLDA_simple_linear_regression": "MCMC",
    "samplers/MLDA_gravity_surveying": "MCMC",
    "samplers/MLDA_variance_reduction_linear_regression": "MCMC",
    "samplers/GLM-hierarchical-jax": "MCMC",
    "splines/spline": "Splines"
}
